### PR TITLE
map fields individual updating

### PR DESCRIPTION
**Pull request by pamnard**

### CODE REVIEW

**Comment by kHorozhanov** [comment]
Hi, @pamnard. Thank you for your improvements!

I have taken a look at these updates.

And it's not working as expected for me.

I have tested with following values:

`const d = { name: "some.nested.property", value: "example value" };`

and input object get `{some: "example value"}` in the result.


But I have asked chat GPT to help with that, this and here is the result, and it works fine for me 😄

Can you please take a look at this code?

```
if (d.name.indexOf('.') !== -1) {
    const nameParts = d.name.split('.');
    let obj = input; // Start with the top-level input object
    for (let i = 0; i < nameParts.length - 1; i++) {
      // Loop until the second last part
      const part = nameParts[i];
      if (!obj[part]) {
        // Create nested object if it doesn't exist
        obj[part] = {};
      }
      obj = obj[part]; // Move to the next level of the object
    }
    obj[nameParts[nameParts.length - 1]] = d.value; // Assign the value to the last part
  } else {
    input[d.name] = d.value;
  }
  ```

**Comment by pamnard** [comment]
Hi @kHorozhanov 
In my version, the line `input[nameParts[0]] = obj;` applies changes to the `input` variable, so the result will be that the following code will be added to the `input` variable:

```
{
   some: {
     nested: {
       property: "example value"
     }
   }
}
```

And in your variant `obj[nameParts[nameParts.length - 1]] = d.value;` you're building a temporary `obj` object, but `input` doesn't change.

**Comment by kHorozhanov** [comment]
@pamnard "obj" referred to the"input", so there shouldn't be any issues with it.

**Comment by kHorozhanov** [comment]
Closed by #4

**Pull request closed without merging**
